Feature/create extension
magma-labs/solidus_payment_method_by_zone pull request #1
Opened 2019-02-11 18:12 UTC by jnegrete

Quick Info
---
This change adds the ability to restrict payment methods by zone, adding the zones to the payment method form and filtering the payment methods in the checkout.

Migrations?
---
:+1:

What does this change?
---
Adds a list the of zones in the payment method form to be filtered in the checkout.

Why are you changing that?
---
To show different payment methods according to the zone.

Merge/Deploy Checklist
---
- [ ] It has been reviewed and accepted.

2019-02-15 17:55 UTC, carlos-araoz commented on config/locales/en.yml
> +  hello: Hello world
Hey @jnegrete is this necessary?

2019-02-15 18:12 UTC, jnegrete commented on config/locales/en.yml
> +  hello: Hello world
@carlos-araoz, not really XD

2019-02-15 18:22 UTC, vzqzac requested changes
Great work! 🎉 There are a few things that came to my eyes while reviewing, aside of the comments, some git tweaks here:

Commit 7755b73e1db9d4e20096401b42f29362725cd9d4 should be splitted, it contains testing setup, which should be done in 8706ebf7e81c88392aeedf8044a90d8447c30c21 already, and it also contains tests for logic that has been added in 2af2bbd7772507d291a2a7ee3b614886a88a142b, the new logic should be paired with its specs, tests should not come later

After that, the commit generated from the `fixup` of splitten 7755b73e1db9d4e20096401b42f29362725cd9d4 and 8706ebf7e81c88392aeedf8044a90d8447c30c21 should be rebased to appear before 2af2bbd7772507d291a2a7ee3b614886a88a142b, this way we would have all the testing setup needed before actually creating tests

Reach me out if you have doubts/want to discuss this/need help! 😄

2019-02-15 18:22 UTC, vzqzac commented on README.md
> +Solidus extension to allow payment methods to be restricted by zones.
Oops, this is a duplicated line

2019-02-15 18:22 UTC, VzqzAc commented on app/models/concerns/solidus_payment_method_by_zone/payment_method.rb
> +    extend ActiveSupport::Concern
Kudos on using concerns!

2019-02-15 18:22 UTC, VzqzAc commented on app/models/spree/order_decorator.rb
> +        .where(spree_payment_method_zones: {zone_id: [nil] + Spree::Zone.for_address(ship_address).map(&:id)})
We could use `Spree::Zone.for_address(ship_address).pluck(:id)` here instead of mapping

2019-02-18 17:32 UTC, vzqzac approved these changes
Great work!

2019-02-18 17:53 UTC, softr8 approved these changes

2019-02-18 17:53 UTC, merged